# Generated by Django 5.1.1 on 2024-12-10 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=100)),
                ('mail_user', models.CharField(max_length=100)),
                ('mdp_user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_org', models.CharField(max_length=100)),
                ('mail_org', models.CharField(max_length=100, unique=True)),
                ('mdp_org', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('lieu', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('capacite', models.IntegerField(default=10)),
                ('organisateur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evenements_organises', to='application.organisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='application.evenement')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='application.participant')),
            ],
        ),
    ]
