# Generated by Django 5.1.1 on 2024-12-10 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
