# Generated by Django 5.1.1 on 2024-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_evenement_date_debut_alter_evenement_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='mdp_user',
            field=models.CharField(max_length=128),
        ),
    ]
