# Generated by Django 5.1.1 on 2024-12-11 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_participant_mdp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la notification.', max_length=100)),
                ('message', models.TextField(help_text='Contenu de la notification.')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, help_text="Date et heure de l'envoi de la notification.")),
                ('lu', models.BooleanField(default=False, help_text='Indique si la notification a été lue par le participant.')),
                ('evenement', models.ForeignKey(help_text="L'événement pour lequel cette notification est envoyée.", on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='application.evenement')),
                ('organisateur', models.ForeignKey(help_text="L'organisateur qui envoie cette notification.", on_delete=django.db.models.deletion.CASCADE, related_name='notifications_envoyees', to='application.organisateurs')),
                ('participant', models.ForeignKey(help_text='Le participant qui reçoit cette notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='application.participant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
