# Generated by Django 5.1.1 on 2024-12-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_participant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
